name: "ai-weather-station"
services:
  web-ai:
    build: .
    container_name: weather-station-ai
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      # Mount folder data dan models agar data tidak hilang saat container restart
      - ./data:/app/data
      - ./models:/app/models
